# Generated by Django 2.2.12 on 2022-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220109_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='timeStamp',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
    ]
