# Generated by Django 2.2.12 on 2022-01-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220110_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
