# Generated by Django 2.2.12 on 2022-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcomment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='time',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
